apiVersion: v1
kind: Service
metadata:
  name: wp-mysql
  labels:
    app: wp-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: wp-mysql
    tier: mysql
  clusterIP: None
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-claim
  labels:
    app: wp-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wp-mysql
  labels:
    app: wp-mysql
spec:
  selector:
    matchLabels:
      app: wp-mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wp-mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL-ROOT-PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-wp-secret
              key: db-pass
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-volume-claim
