apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-1
  labels:
    type: volume
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/volumes/volume-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-2
  labels:
    type: volume
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/volumes/volume-2
