apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wp
spec:
  ports:
    - port: 80
  selector:
    app: wp
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-volume-claim
  labels:
    app: wp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wp
spec:
  selector:
    matchLabels:
      app: wp
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wp
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: DB_HOST
          value: wp-mysql
        - name: DB_ROOT_PASSWORD
          value: test123
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-volume-claim
